### ISSUE TITLE
Create PR on XKCP.Net

### ISSUE THREAD

**Issue by Rjvs** [StirlingLabs/XKCP#5]
Once a successful build is created and packaged up, we want to add the libraries to [StirlingLabs/XKCP.Net](https://github.com/StirlingLabs/XKCP.NET).  I'm thinking that the process could be:

- Check out the XKCP.Net repo
- Create a branch
- Copy the libs into the appropriate location
- Push the new branch
- Create a PR against Master using the new branch

Then after that, the CI/CT/CD on the XKCP.Net side will kick in and test that the libs work and flag that PR as being okay.

We do some of this in [StirlingLabs/StirlingData](https://github.com/StirlingLabs/StirlingData) when creating the autoprotorepo-csharp repositories from generated code but don't currently create pull requests.  There are a heap of Actions that will [create](https://github.com/marketplace/actions/create-pull-request) and [update](https://github.com/marketplace/actions/create-or-update-pull-request) PRs though, so that should be fairly straightforward.

I haven't looked at any of the PR Actions so you should evaluate them before picking one but also you might be able to use them to create a PR directly without going through all of the correct git steps, which might be more efficient or at least have less steps.

**Comment by TYoungSL** [comment]
When PR #8 is merged, this issue should be good to close.
