### ISSUE TITLE
Periodically sync with Upstream

### ISSUE THREAD

**Issue by Rjvs** [StirlingLabs/XKCP#6]
- We should periodically (on Monday & Thursday each week) check if there are new commits on the upstream `XKCP/XKCP/master` branch.
- If there are new commits upstream, we should create a PR to merge them from `XKCP/XKCP/master` into `StirlingLabs/XKCP/master`.  
- If there is already a PR from a previous update that hasn't already been merged, that PR should just be updated and no new PR created.

The [Create PR from upstream repos for private forks](https://GitHub.com/marketplace/actions/create-pr-from-upstream-repos-for-private-forks)	Action looks like it does exactly this, although it has 0 stars.  The [Create Sync PR](https://github.com/marketplace/actions/create-sync-pr) Action first creates a tracking branch and then creates a PR from that, which leaves a branch that we have to delete.

**Comment by Rjvs** [comment]
This same functionality will be required for meshoptimizer, MeshOptimizer.Net, OCCT, rvmparser, etc.  (they will all need to acquire stirling-labs branches or equivalent).

**Comment by ilkerhalil** [comment]
Waiting for you to merge this previous pr for this job

**Comment by Rjvs** [comment]
Just confirming that #5 (and hence #8) are both entirely separate from this issue.  So long as we aren't committing any changes to `master` (we don't, all of our changes go into `Stirling-labs`) then I don't see why there should be any clash between our master and upstream/master.  I've created a discussion of this issue at https://github.com/orgs/StirlingLabs/teams/devops/discussions/2 so we can make sure everyone understands what we're doing.

**Comment by TYoungSL** [comment]
Holding this issue open until we run a release from upstream XKCP all the way to XKCP.NET.

**Comment by Rjvs** [comment]
@ilkerhalil Has there been any commit that address this issue?

**Comment by TYoungSL** [comment]
Note we are using `master` as the main instead of `stirling-labs` now, we won't hang on to the upstream master branch anymore.

**Comment by TYoungSL** [comment]
Following up with https://github.com/StirlingLabs/XKCP/commit/eaf322d373b2ca10568c88c83ec6ff1d06a0c37e
